package pojo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 6 dic 2022, 13:09:25 by Hibernate Tools 5.5.9.Final

/**
 * Zoologicos generated by hbm2java
 */
@Entity
@Table(name = "zoologicos")

public class Zoologico implements java.io.Serializable {
	
	@Id 
	@Column (name ="id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;
	@Column (name ="nombre", unique = true, nullable = false, length =40 )
	private String nombre;
	@Column (name ="ciudad", nullable = false, length =40 )
	private String ciudad;
	@Column (name ="anyo_fundacion")
	private int anyoFundacion;

	public Zoologico() {
	}

	public Zoologico( String nombre, String ciudad, int anyoFundacion) {
		this.nombre = nombre;
		this.ciudad = ciudad;
		this.anyoFundacion = anyoFundacion;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public int getAnyoFundacion() {
		return this.anyoFundacion;
	}

	public void setAnyoFundacion(int anyoFundacion) {
		this.anyoFundacion = anyoFundacion;
	}

}
